# The organization using GitHub Classroom
organization = ""

# The prefix of user repos, i.e. user repos should have a format of prefix-username
prefix = ""

# The workspace of user repos and template repo
workspace = ""

# The name of template repo, under the same organization
template = ""

# The branch of template repo, default to master
template_branch = ""

# The output csv file to store grades
result = ""

# The students csv having three columns: student id, real name and GitHub user name.
students = "students.csv"

# The path to python3 script grader
grader = "grade.py"

# The file to diff in Diff panel
diff = "code.py"

# The file or directory to overwrite from template to user before grading
copy = ["grade.py"]

# Run anything before grading?
# before_grader = "./scripts/gen_output.sh"

# Homework deadline
# deadline = "2021-09-02 00:00:00 +08:00"
